name: FTP Deploy + Auto‑Unzip

on:
  workflow_dispatch:

jobs:
  ftp_deploy:
    uses: ./.github/actions/ftp-deploy
    with:
      zip_source:     'demo-data/'
      ftp_host:       ${{ secrets.FTP_HOST }}
      ftp_user:       ${{ secrets.FTP_USER }}
      ftp_password:   ${{ secrets.FTP_PASSWORD }}
      ftp_remote_path: '/uploads/test'
      php_script_url: 'https://static.bridge.cz/uploads/test/'
